#!/bin/sh -e

##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}

cmd='ls -l Results/12-hisat2-align'
printf "Running $cmd...\n"
pause

$cmd | more
cmd='more Logs/12-hisat2-align/*.err'
printf "Running $cmd...\n"
pause
$cmd
